Correct missing ENV for deployment action for pre-release
zowe/zowe-cli-secrets-for-kubernetes pull request #22
Opened 2023-08-28 16:38 UTC by rudyflores

**What It Does**

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2023-08-28 19:54 UTC, zFernand0 reviewed
let's hold off on updating these as the secrets have not being added yet...
any thoughts on the following secrets as Organization secrets?
```
VSCODE_VSCE_PUBLISHER_TOKEN
VSCODE_OVSX_PUBLISHER_TOKEN
```

2023-08-28 20:24 UTC, rudyflores commented
> 

These ENV names sound good to me!

2023-08-29 18:30 UTC, zFernand0 commented
Quick update:
we got the tokens added:

![image](https://github.com/zowe/zowe-cli-secrets-for-kubernetes/assets/37381190/a2ba3cae-7ce0-4f14-ba0c-df05571b2d77)

2023-08-30 12:35 UTC, zFernand0 requested changes

2023-08-30 12:35 UTC, zFernand0 commented on .github/workflows/zowe-cli-plugin.yml
> +                  VSCE_PAT: ${{ secrets.VSCODE_PUBLISHER_TOKEN }}
Could we change the secret ENV vars to the ones mentioned above?

2023-08-30 19:11 UTC, traeok approved these changes
LGTM, thanks @rudyflores!

2023-08-31 14:34 UTC, zFernand0 approved these changes

2023-08-31 14:35 UTC, merged