solve tough-cookie dependency issue
zowe/zowe-cli-secrets-for-kubernetes pull request #33
Opened 2024-01-10 18:17 UTC by rudyflores

**What It Does**

Solves #32 

Updated outdated dependencies, bumped npm version to `9.8.1` and node to `18.18.2` in order to provide supported versions since 16 seems to have reached [EOL](https://endoflife.date/nodejs).

this fix for `tough-cookie` dependency will use the `@kubernetes/client-node` version `1.0.0-rc4`of the API in order to use the fetch implementation mentioned in their repo instead of the deprecated and now vulnerable package of `request` the version `0.20.0` has. Once `v1.0.0` is released we can bump that version to that, but for the time being this can be used as a temporary fix for a critical vulnerability.

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2024-01-10 19:23 UTC, t1m0thyj approved these changes

2024-01-10 19:23 UTC, t1m0thyj commented on packages/vscode/package.json
Should we update the changelog for the "vscode" package too? Even though nothing has changed (besides the dev dep), I assume we want to publish a new version that uses the updated CLI package.

2024-01-10 19:23 UTC, t1m0thyj commented on .github/workflows/zowe-cli-plugin.yml
> +                node-version: [18.x]
Should we add 20.x to the list since that's also currently a supported LTS version?

2024-01-10 19:24 UTC, zFernand0 approved these changes
thanks for updating so many dependencies 😋

2024-01-10 19:26 UTC, t1m0thyj requested changes
Sorry I may have approved prematurely - noticed that system tests in the Ubuntu build started failing with:
```
Error: 24/01/10 19:23:36.160] [ERROR] [CredentialManagerFactory.js:149] Failed to load the credential manager named "Secrets for Kubernetes"
Error: 24/01/10 19:23:36.167] [ERROR] [CredentialManagerFactory.js:151] Error: Namespace default does not exist
```

Maybe fixing https://github.com/zowe/zowe-cli-secrets-for-kubernetes/issues/15 would help to troubleshoot this - I suspect the real error isn't "Namespace does not exist", but something else which is currently hidden from the error message.

2024-01-10 19:49 UTC, rudyflores commented on .github/workflows/zowe-cli-plugin.yml
> +                node-version: [18.x]
That sounds good to me!

2024-01-10 19:50 UTC, rudyflores commented
> Sorry I may have approved prematurely - noticed that system tests in the Ubuntu build started failing with:
> 
> ```
> Error: 24/01/10 19:23:36.160] [ERROR] [CredentialManagerFactory.js:149] Failed to load the credential manager named "Secrets for Kubernetes"
> Error: 24/01/10 19:23:36.167] [ERROR] [CredentialManagerFactory.js:151] Error: Namespace default does not exist
> ```
> 
> Maybe fixing #15 would help to troubleshoot this - I suspect the real error isn't "Namespace does not exist", but something else which is currently missing from the error message.

Seems to be related to self signed certs, I'm looking into refactoring some code across the `K8sCredentialManager.ts` file to prevent this

2024-01-16 14:13 UTC, traeok approved these changes
Code LGTM, will quickly test & update the review if something comes up. Thanks @rudyflores!

2024-01-16 16:39 UTC, merged